name=inverterLib
version=0.1.0
author=Pedro Akio Sakuma
maintainer=Pedro Akio Sakuma <pedrosakuma11@gmail.com>
sentence=Modbus RTU library for Arduino/ESP8266 focused on inverter communication with flexible register mapping.
paragraph=Lightweight and structured Modbus RTU (RS485) library designed for inverter communication. Supports multiple devices on the same bus, configurable register maps, blocking reads with timeout, and decoding of various data types (U16, U32, I32, FLOAT32, ASCII). Includes abstraction layers for inverter logic, Modbus configuration, and register descriptors, enabling scalable and maintainable implementations.
category=Communication
url=https://github.com/akioShaolin/ModbusInverterLib
architectures=esp8266,esp32
license=BSD-3-Clause
depends=ModbusRTU